name: TemporalBlocks
version: ${version}
description: ${description}
main: me.mapacheee.temporalblocks.TemporalBlocksPlugin
api-version: 1.21
author: mapacheee
website: https://github.com/Mapacheee

permissions:
  temporalblocks.admin:
    description: Admin perms
    default: op
  temporalblocks.bypass:
    description: bypass temporalblocks
    default: false

commands:
  temporalblocks:
    description: Commands for temporal blocks
    usage: /temporalblocks <reload|info>
    permission: temporalblocks.admin
    aliases: [tb, tblocks]
